🎉 init: Set up initial newspeed-app project structure
happy-hooky/newspeed-app pull request #6
Opened 2023-07-27 06:57 UTC by beolggoolosori

# expo 세팅 커밋입니다🧐 

## 디렉토리 구조

```
/newspeed-app
├── .expo
├── my-app
│   ├── assets
│   ├── node_modules
│   ├── src
│   │   ├── components
│   │   │   ├── atoms
│   │   │   ├── molecules
│   │   │   ├── organisms
│   │   │   ├── templates
│   │   │   └── pages
│   │   ├── navigation
│   │   ├── services
│   │   ├── types
│   │   ├── utils
│   │   └── App.tsx
│   ├── app.json
│   ├── tsconfig.json
│   └── package.json
│   └── package-lock.json
```

## Design Pattern

Atomic Design 패턴을 이용하여 앱의 디렉토리 구조를 설정하였습니다. 

## Dependencies

```
    "@react-navigation/bottom-tabs": "^6.5.8",
    "expo": "^49.0.5",
    "expo-status-bar": "~1.4.4",
    "react": "18.2.0",
    "react-icons": "^4.10.1",
    "react-native": "0.71.8",
    "react-native-vector-icons": "^10.0.0"
```

## Test

`Expo CLI`를 사용하여 로컬 환경에서 테스트했습니다.
`npm start` 를 실행하여 **ios** 및 **android** 플랫폼에서 정상적으로 동작하는지 확인했습니다.

### 피드백 부탁드립니다.

2023-07-27 12:37 UTC, white-gyu commented
슬랙 알림 테스트!

2023-07-27 12:54 UTC, white-gyu commented
슬랙 알림 테스트!

2023-07-28 07:47 UTC, imzeze requested changes

2023-07-28 08:36 UTC, imzeze approved these changes

2023-07-29 15:02 UTC, merged